# Generated by Django 3.2.3 on 2024-04-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Area Name')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Building Name')),
            ],
        ),
        migrations.CreateModel(
            name='MasterProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Master Project')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Building Name')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Propery Type')),
            ],
        ),
        migrations.CreateModel(
            name='RoomsNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Number of Rooms')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200, verbose_name='Transaction ID')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('object_price', models.FloatField(blank=True, null=True, verbose_name='Object Price')),
                ('object_size', models.FloatField(blank=True, null=True, verbose_name='Object Size')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.areaname')),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buildingname')),
                ('master_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.masterproject')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.projectname')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.propertytype')),
                ('rooms_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.roomsnumber')),
            ],
        ),
    ]
