# Generated by Django 3.2.3 on 2024-05-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_objecttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='PropertyUsage')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='RegistrationType')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='TransactionGroup')),
            ],
        ),
        migrations.AlterModelOptions(
            name='realestate',
            options={'ordering': ('-transaction_date',)},
        ),
        migrations.AddField(
            model_name='realestate',
            name='property_usage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.propertyusage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestate',
            name='registration_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.registrationtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestate',
            name='transaction_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.transactiongroup'),
            preserve_default=False,
        ),
    ]
